### ISSUE TITLE
Problem in documentation

### ISSUE THREAD

**Issue by cyrilmayance** [AlexanderDickie/auto-selfcontrol-rs#1]
Thanks for creating this tool!

Tiny correction that's necessary in your README.md file: it says `./auto-self-control-rs --write_example_config` when it should say `./auto-selfcontrol-rs --write_example_config` (No hyphen between "self" and "control").

Other than that, great tool! IMHO, the next great thing would be the ability to define a daily schedule, the way the "original" scheduler does. Thanks again!

**Comment by AlexanderDickie** [comment]
ah yes thanks for pointing that out, and thanks, glad you like it! 

a daily schedule as in each block can have its own blocklist, so for example you could specify something like this in the config?:
["9:00", "12:00"] : ["google.com", "facebook.com"],
["15:00", "1:00"] : ["youtube.com"],
hence only google and facebook are blocked between 9-12, and then only youtube is blocked from 3pm-1am

**Comment by cyrilmayance** [comment]
You're welcome!
It's mostly the ability to define a different schedule for each day of the week. In the json file of the "original" tool, you can define blocks like this:
` "block-schedules":[
        {
            "weekday": 1,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },`

I find it super useful if I want to, let's say, block some sites during the week and not during the weekend.
Also, your suggestion for each block to have its own blocklist would be awesome as well.
Thanks!

**Comment by AlexanderDickie** [comment]
Thats a good idea thanks, I'll implement it in the next week or so

**Comment by AlexanderDickie** [comment]
> 

check out the new release

**Comment by cyrilmayance** [comment]
Thanks very much for the update and for implementing the feature!

Small error that I caught:  the folder that gets generated during the _"--write_example_config"_ phase has an extra hyphen "auto-self-control-rs" when, according to your documentation, it should be "auto-selfcontrol-rs".
However, the _"--deploy"_ phase works with the hyphen in the folder's name, and doesn't work without it.

**Comment by AlexanderDickie** [comment]
ah yes, thanks for finding that, fixed
