### ISSUE TITLE
--deploy generates bad .plist

### ISSUE THREAD

**Issue by HotwheelsSisyphus** [AlexanderDickie/auto-selfcontrol-rs#2]
Hi, thanks for your work on this! 
I've been trying to get it running (macos 12.6.3 on a 2017 MB air), following the instructions for Intel macs. It initially didn't work for me (i.e., launchagent just wouldn't load), but today I took a closer look at the .plist file that is being generated by --deploy, and it turns out that's where the issue is:

`plutil ~/Library/LaunchAgents/com.main-auto-selfcontrol-rs.plist` 
returns
`/Users/tt/Library/LaunchAgents/com.main-auto-selfcontrol-rs.plist: Found non-key inside <dict> at line 24`
  
the faulty plist looks like this, line 24 is the end of the second `<dict>` entry after `StartCalendarInterval`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.main-auto-selfcontrol-rs.plist</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Users/tt/auto-selfcontrol-rs</string>
        <string>--execute</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>0</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>8</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>10</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>12</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>14</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>16</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>18</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>20</integer>
    </dict>
    <dict>
        <key>Minute</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>22</integer>
    </dict>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

 I'm pretty new to all this, but googling the error message suggests that each `<dict>` entry should be preceded by some key, presumably `<key>StartCalendarInterval</key>`, and if I edit the plist accordingly `plutil` tells me it's OK; and I can `launctl load` it succesfully, and it does start a block, etc.

so this might be an easy fix?

**Comment by AlexanderDickie** [comment]
Hi, 
Thanks for pointing that out, thats a very significant bug, I've just been using one block everyday and didnt realize it broke for >1 blocks.
Wrapping the all the dicts that specify the block start times together in an single vector fixes the plist.
I've fixed + re-uploaded the binary so curl it again and it should be good

**Comment by HotwheelsSisyphus** [comment]
Thanks for the quick response! It seems to be working fine now with multiple blocks per day.
Sometimes it seems like it's still not starting certain blocks but 
a) this happens only occasionally and
b) I haven't been paying very close attention so it might be something on my end (the last few days have been a mess - haven't had electricity at home since Wednesday night). I'll keep observing.

Anyway, thanks so much for this tool! These days, one needs all the help one can get to push back against all the social media and hyperinformation nonsense...

**Comment by AlexanderDickie** [comment]
I agree they're so addictive, i feel kind of relieved when I have the blockers on and I'm cant surf yt etc... And the selfcontrol app seems to be the only blocker you cant turn off (or at least its very hard to). 
I also have a system setup for my ios devices where i use a rasp pi as a bluetooth keyboard emulator to send a screentime password i dont know to my devices which works well.  

Yeh please comment again if you find another block it doesn't start or any other bugs you find.
