### ISSUE TITLE
Not an issue or bug but I just wanted to say thank you for making this.

### ISSUE THREAD

**Issue by Yoyopizzacat** [AlexanderDickie/auto-selfcontrol-rs#4]
thank you for your service kind sir. the other one did not work but this is perfect. thank you so much

**Comment by AlexanderDickie** [comment]
thank you! glad you like it

**Comment by liam-k** [comment]
This is closed already, but I just found this and want to say the same! auto-selfcontrol has been broken for ages and as someone with no actual self control, my life has been worse for it.😅 So I’m really glad someone took care of that! Thank you!!
